### ISSUE TITLE
Metadata

### ISSUE THREAD

**Issue by ethancohen123** [gigascience/paper-bray2017#11]
Hi,
How can we access the metadata per plates ? It supposed to be on some extension ( indicated in the webpage ) but I don’t see how can one download them, can you please explain the process here ?
Thank you

**Comment by only1chunts** [comment]
All the data that we host is available from the dataset file store, you can access that directly here https://ftp.cngb.org/pub/gigadb/pub/10.5524/100001_101000/100351/ or via the dataset files tab  http://dx.doi.org/10.5524/100351 (each file has a hyperlink on the filename to enable download as well as a download button in the right-hand column). 

There is a file called "chemical_annotations.csv" which has the description "Table containing metadata for many of the compounds from Broad Institute’s Chemical Biology Informatics Platform (CBIP), including (where applicable) compound names, simplified molecular-input line-entry system annotations (SMILES), MLSMR sample identifiers, and PubChem compound identifiers (CID) and substance identifiers (SID). The latter two items are useful for querying the PubChem Compound Database (http://www.ncbi.nlm.nih.gov/pccompound)."
Maybe that is the metadata you are looking for? 

Or maybe its the files that are stored in the directory called "profiles.dir" ?https://ftp.cngb.org/pub/gigadb/pub/10.5524/100001_101000/100351/profiles.dir/

Please note, we only host the data, we have no expertise in it and had nothing to do with its generation, hence I dont understand which "metadata" you are looking for. If you require something that we do not have you will need to contact the dataset submitter using the contact submitter button on the dataset page.

**Comment by ethancohen123** [comment]
l

**Comment by ethancohen123** [comment]
![metadat](https://user-images.githubusercontent.com/55588944/167383907-36c5fb4b-cbef-4539-948e-bc0867a7a8f2.PNG)

I'm mentionning those metadata and I guess it should be also on gigaDB . It is just that I can't find the way to dowload them.

Thanks for your help
Ethan

**Comment by pli888** [comment]
@ethancohen123 Try reaching out to the authors - they have been responsive in the [past](https://github.com/gigascience/paper-bray2017/issues/7).

**Comment by only1chunts** [comment]
@ethancohen123 the files you are looking for are included in each of the plate tar-balls, e.g.
Plate_26569.tar.gz (available from https://ftp.cngb.org/pub/gigadb/pub/10.5524/100001_101000/100351/Plate_26569.tar.gz )
contains the subdirectories listed in your screenshot:
![image](https://user-images.githubusercontent.com/6037145/167391749-53e99ed8-4311-4e01-b207-107f11c34183.png)

I hope that is what you are looking for?

**Comment by ethancohen123** [comment]
Yes that is what I am looking for thanks !
So if I dowload the plate number x I should have some folder included right ?

**Comment by only1chunts** [comment]
correct. Each plate "file" e.g.  https://ftp.cngb.org/pub/gigadb/pub/10.5524/100001_101000/100351/Plate_26569.tar.gz is infact an archive of multiple files. Once downloaded you will need to extract the tar-ball archive using a suitable tool. If you are familiar with command line then the tar -zxf <filename> is recommended. If you are not using the comand line then you may need to google the most appropriate method for your opperating system (in windows I use a tool called 7-Zip).

**Comment by ethancohen123** [comment]
Everything works fine I've uploaded one as example all good , thank you !
