### ISSUE TITLE
Possible to download only morphological profiles?

### ISSUE THREAD

**Issue by sgfin** [gigascience/paper-bray2017#3]
Hi there,

I'd like to use the morphologic profiles from this experiment rather than the images themselves.  However, it appears that it's impossible to download these directly -- only by downloading a whole image folder and then pulling out the profile file and catting them all together.  Given the large size of all the .gz files, and the fact an advertised use is pretraining on just the morphological profiles, is there any way to download just the profiles themselves?

Thanks,
Sam

**Comment by only1chunts** [comment]
Hi @sgfin , please can you provide the dataset DOI that you are referring to?

**Comment by pli888** [comment]
@only1chunts I think it is this one: [http://dx.doi.org/10.5524/100200](
http://dx.doi.org/10.5524/100200)

**Comment by only1chunts** [comment]
Thanks Peter, FYI the new version of that dataset is 100351.
I can see ~400 tar.gz files, each containing a bunch of files. Unfortunately there is none that are helpfully called "morphological profile" so I dont know exactly which files are of particular interested?
@sgfin , if you can tell me which file in the example list below would be of interest to you I can extract that file-type from each of the tar.gz archives and save them as a single tar.gz file in the dataset, will that help?

gigascience_upload/Plate_26795/profiles/mean_well_profiles.csv
gigascience_upload/Plate_26795/illumination_correction_functions/26795_IllumRNA.mat
gigascience_upload/Plate_26795/illumination_correction_functions/26795_IllumMito.mat
gigascience_upload/Plate_26795/illumination_correction_functions/26795_IllumDNA.mat
gigascience_upload/Plate_26795/illumination_correction_functions/26795_IllumER.mat
gigascience_upload/Plate_26795/illumination_correction_functions/26795_IllumAGP.mat 
gigascience_upload/Plate_26795/extracted_features/26795.sqlite 
gigascience_upload/Plate_26795/quality_control/qc.csv

**Comment by sgfin** [comment]
Thanks, both.  Based on Table 2 in the accompanying article (https://academic.oup.com/gigascience/article/6/12/giw014/2865213), I think what I'm looking for is:

`*/profiles/mean_well_profiles.csv`

Downloading one sample gz, it looks like the total dataset size is ~4TB but that a catted together file of the "mean_well_profiles" would be <1GB, but I don't see a simple way to access without downloading all the images.

**Comment by only1chunts** [comment]
you are correct, there is no simple way to pull just specific files from within multiple tar.gz archive files, we had not envisaged user requirement for the particular subset of files you are after. I can script something to extract those files on our server, I will let you know when I have them all done.

**Comment by sgfin** [comment]
Wow thank you so much!

**Comment by shntnu** [comment]
@only1chunts Thank you for looking into this! Let me know if I can help (I'm a de facto corresponding author on this paper)

**Comment by only1chunts** [comment]
Hi,
the profile files are all now available to download in this tar archive:
ftp://parrot.genomics.cn/gigadb/pub/10.5524/100001_101000/100351/profiles.tar.gz (2.1GB)
I will add that file to the dataset, could you suggest an appropriate description of the file?

**Comment by sgfin** [comment]
Wonderful.  Based on Table 2 of the [paper](https://academic.oup.com/gigascience/article/6/12/giw014/2865213), I'd say something like "morphological profiles" is a great name.

Thanks again

**Comment by shntnu** [comment]
The data has been described in Table 2 [here](https://academic.oup.com/gigascience/article/6/12/giw014/2865213#120204628)

Data item | Location | Description
-- | -- | --
Morphological profiles | GigaDB: <plate_ID>/profiles | Per-well averages of each extracted morphological feature computed across the cells.

so the file name profiles.tar.gz works well. You can copy the description from the table

**Comment by only1chunts** [comment]
Thanks, I've added it to the file list and included the md5checksum value too
305a84bd287945f31aa8b73d9542c079  ./profiles.tar.gz

**Comment by shntnu** [comment]
I note here that there are additional ways of getting the profiles:

1. **Individual tar.gz. files**, one per plate; details [here](https://academic.oup.com/view-large/120204621). The file sizes are shown [here](https://github.com/gigascience/paper-bray2017/files/6200051/2015_Bray_GigaScience_gigascience_upload_targz_file_list.txt)

```sh
parallel -a \
    CDRP_plates.txt \
    aws s3 cp \
    --request-payer requester  \
    s3://imaging-platform-requester-pays/projects/2015_Bray_GigaScience/gigascience_upload_targz/{1}
```
[CDRP_plates.txt](https://github.com/gigascience/paper-bray2017/files/6200034/CDRP_plates.txt)

2. **Single tar.gz file**, comprising aggregated and normalized per-well CSV files for each of the 406 plates in the dataset. 
e.g. For plate 25414, we have
- CDRP/25414/25414_augmented.csv - per-well means
- CDRP/25414/25414_normalized.csv - per-well means that are robust z-scored ( (x - median(x)) / mad(x) ) w.r.t a reference distribution. The reference distribution is the per-cell DMSO values.
Download it [here](https://imaging-platform-collaborator.s3.us-east-1.amazonaws.com/CDRP/CDRP.tar.gz) (4.2GB)

**Comment by cyli029** [comment]
> Thanks, I've added it to the file list and included the md5checksum value too 305a84bd287945f31aa8b73d9542c079 ./profiles.tar.gz

How to download this file？It may not be found on http://gigadb.org/dataset/view/id/100351/

**Comment by only1chunts** [comment]
It is there in dataset 100351, but the direct download link for it is now:
https://s3.ap-northeast-1.wasabisys.com/gigadb-datasets/live/pub/10.5524/100001_101000/100351/profiles.tar.gz

**Comment by cyli029** [comment]
Thank you for providing the updated direct download link for this dataset. I appreciate your help and the prompt response.
