### ISSUE TITLE
Missing dependencies?

### ISSUE THREAD

**Issue by nbenn** [gigascience/paper-bray2017#5]
I'm currently looking into `analysis.cppipe`, more specifically at the `FlagImage` module and I was wondering how to get access to the two files `is_saturated_rules.txt` and `is_blurry_rules.txt`. As far as I understand, they are not created by the `quality_control.cppipe` pipeline, right? Would it be possible to commit these two files to this repo? Or can I download them from somewhere?

**Comment by pli888** [comment]
@nbenn From the [Singh et al., (2015)](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0131370) paper, those 2 files are available in a [zip file](https://doi.org/10.1371/journal.pone.0131370.s001).
