### ISSUE TITLE
wget: connection timed out

### ISSUE THREAD

**Issue by karreny** [gigascience/paper-bray2017#6]
I am unable to download the dataset using provided script (download_cil_images.sh). wget times out, and I am also unable to download the individual .zip files via my browser. Could you please confirm if these urls are still up-to-date? Thanks

**Comment by pli888** [comment]
Hi @shntnu can you check the status of the http://ccdb-portal.crbs.ucsd.edu:8080/broad_data/plate_* URLs please?

**Comment by yala** [comment]
I had the same problem but I think I figured it out,
change the base URL from  `http://ccdb-portal.crbs.ucsd.edu:8080/`  to  `https://cildata.crbs.ucsd.edu/` and it now works and downloads fine. 

I got this from poking around the broad website and seeing where the download path was.

**Comment by shntnu** [comment]
I'm not sure why I didn't get a GitHub notification for https://github.com/gigascience/paper-bray2017/issues/6#issuecomment-558416624 but I'm glad @yala figured it out. 

Fixed in #8

**Comment by shntnu** [comment]
@pli888 This issue is now resolved

**Comment by shntnu** [comment]
@ved-sharma This data is now available on an S3 bucket. See https://github.com/broadinstitute/cellpainting-gallery/issues/13 for more 

Read https://github.com/broadinstitute/cellpainting-gallery/blob/main/folder_structure.md to get oriented to the data
