### ISSUE TITLE
Meaning behind plate group labels?

### ISSUE THREAD

**Issue by nishanthmerwin** [gigascience/paper-bray2017#7]
During my investigation with this data set, I wanted to see if there were any systemic biases present. In order to do so, I first began looking at plate specific effects, and then progressed towards the plate groups identified (`Metadata_Plate_Map_Name` in the processed features data set). I sorted these alphabetically, and noticed there were larger trends present across plate groups. By splitting the plate group names by hyphens, I noticed that these groups were highly correlated to plate similarity (see attached figure). However, I’m not sure what the actual meaning behind these labels!

Questions:
- What is the meaning between `C` and `H` in the first portion of the label? The `C` plates seem to group strongly together.
- What is the meaning behind the remaining portions of these plate groups? Are they freezer locations? Were they run during the same day?
- Why do some plate groups contain more than 4 plates (e.g. see plates ~130-175 in figure, column 5)?

![heatmap_w_legend](https://user-images.githubusercontent.com/12243430/70350008-dee26880-1833-11ea-8e26-ffad4fa7b7e9.png)

**Comment by pli888** [comment]
Hi @nishanthmerwin. I suggest contacting the authors of the [Bray et al., (2017)](https://academic.oup.com/gigascience/article/6/12/giw014/2865213) paper for answers your questions.

**Comment by nishanthmerwin** [comment]
Thanks @pli888, we'll try reaching out.

**Comment by nishanthmerwin** [comment]
The authors were able to respond, a further investigation can be found here: https://github.com/broadinstitute/imaging-bbbc/issues/61#issuecomment-567542733

**Comment by pli888** [comment]
I'm glad you got a constructive response.
